apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-sem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: end-sem
  template:
    metadata:
      labels:
        app: end-sem
    spec:
      containers:
      - name: end-sem
        image: anirudh30/end-sem:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
